name: 'aiida'
seed: 12345
train_file: 'training.xyz'
valid_file: 'validation.xyz'
test_file: 'test.xyz'
default_dtype: float32
model: MACE
compute_stress: True
energy_key: 'dft_energy'
forces_key: 'dft_forces'
stress_key: 'dft_stress'
stress_weight: 100
hidden_irreps: '128x0e+128x1o'
r_max: 10.4
batch_size: 1
max_num_epochs: 20
swa: True
start_swa: 5
ema: True
ema_decay: 0.99
amsgrad: True
patience: 10
device: cuda
loss: 'universal'
error_table: PerAtomRMSEstressvirials
keep_isolated_atoms: True
save_cpu: True
