name: "aiida"
seed: 12345
default_dtype: float64
model: MACE
compute_stress: True
enable_cueq: True
energy_key: "dft_energy"
forces_key: "dft_forces"
stress_key: "dft_stress"
num_interactions: 2
r_max: 4.5
batch_size: 1
max_num_epochs: 40
swa: True
start_swa: 15
ema: True
ema_decay: 0.99
amsgrad: True
patience: 1000
restart_latest: True
device: cuda
loss: "universal"
error_table: PerAtomRMSEstressvirials
keep_isolated_atoms: True
save_cpu: True