name: "aiida"
seed: 12345
default_dtype: float32
model: MACE
compute_stress: True
energy_key: "dft_energy"
forces_key: "dft_forces"
stress_key: "dft_stress"
stress_weight: 100
hidden_irreps: "128x0e+128x1o"
num_interactions: 2
r_max: 4.5
batch_size: 5
max_num_epochs: 500
swa: True
start_swa: 350
ema: True
ema_decay: 0.99
amsgrad: True
patience: 10
restart_latest: True
device: cuda
loss: "universal"
error_table: PerAtomRMSEstressvirials
keep_isolated_atoms: True
save_cpu: True